{{- range $key, $value := $.Values.vmpodscrape }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: vmpodscrape-{{ $key }}
spec:
  {{- toYaml $value | nindent 2 }}
{{- end }}
