{{- range $key, $value := $.Values.vmstaticscrape }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: vmstaticscrape-{{ $key }}
spec:
  {{- toYaml $value | nindent 2 }}
{{- end }}
